apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: "rohitgabriel/open-liberty:sample"
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app: sample-service
spec:
  type: LoadBalancer
  ports:
    - port: 9080
  selector:
    app: sample-app
