# Default values for bluecompute-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.io/rohitgabriel/open-liberty
  tag: sample
  pullPolicy: Always
service:
  name: sample-service
  type: NodePort
  externalPort: 9080
  internalPort: 9080
  nodeport:
    port:
ingress:
  hostname:
  path: /
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi
region:
clusterName:
services:
  auth:
    protocol:
    host:
    port:
  catalog:
    protocol:
    host:
    port:
  customer:
    protocol:
    host:
    port:
  orders:
    protocol:
    host:
    port:
  reviews:
    protocol:
    host:
    port:

global:
  bluemix:
    apiKey:

    target:
      endpoint:
      org:
      space:

    clusterName:
